---
- hosts: default
  vars:
    bosh_path: "/home/ubuntu/bosh"
  tasks:
  - name: Install system packages
    sudo: yes
    apt: pkg={{ item }} state=present update_cache=yes
    with_items: [ git, tmux, vim ]

  - name: Remove BOSH folder if exists
    shell: "rm -rf {{ bosh_path }}"
    sudo: no

  - name: Try to clone BOSH repository
    sudo: no
    git: "repo=https://github.com/Altoros/bosh.git"
    args:
      accept_hostkey: yes
      version: power-2915
      recursive: yes
      dest: "{{ bosh_path }}"
